package event.useCases;

import account.entities.User;
import account.useCases.AccountManager;
import event.entities.Event;
import room.RoomManager;

import java.util.ArrayList;
import java.util.List;

/**
 * A UserEventManager for a speaker.
 */
public class SpeakerEventManager extends UserEventManager {
    /**
     * Constructs a new UserEventManager with a Speaker.
     *
     * @param user An instance of Speaker.
     */
    public SpeakerEventManager(User user, RoomManager rm) {
        super(user, rm);
    }

    /**
     * Return an ArrayList of Integer of ids of all attendees in this speaker's talks.
     *
     * @param myEvents An ArrayList of Event the speaker holds.
     * @return An ArrayList of Integer of attendee ids in allEvents.
     */
    public List<Integer> getAttendees(List<Event> myEvents) {
        ArrayList<Integer> result = new ArrayList<>();
        for (Event event : myEvents) {
            //get all attendees of the event
            ArrayList<Integer> lst = (ArrayList<Integer>) event.getAttendees();
            //check whether each attendees' id is in result, put the id in result if it is not in the result.
            for (int id : lst) {
                if (!result.contains(id)) {
                    result.add(id);
                }
            }
        }
        return result;
    }

    /**
     * Return an ArrayList of Integer ids of the attendees of an event.
     *
     * @param event An Event the speaker holds.
     * @return A List of Integer attendee ids.
     */
    public List<Integer> getAttendees(Event event) {
        return event.getAttendees();
    }

    /**
     * Return an ArrayList of Integer ids of the events the speaker holds.
     *
     * @param eb An instance of EventBoard.
     * @return A List of Integer event ids.
     */
    public List<Integer> getMyEventList(EventBoard eb) {
        return eb.getSpeakerEvents(user.getId());
    }

    public List<List<String>> getMySchedule(EventBoard eb) {
        List<Event> eventList = eb.getAllEventsById(getMyEventList(eb));
        return scheduleGenerator.scheduleInfo(eventList);
    }

    /**
     * Return an ArrayList of ArrayList of Strings of information of talks hold by this speaker.
     *
     * @param eb  An EventBoard.
     * @param acm An AccountManager.
     * @return An ArrayList of ArrayList of Strings of event information generated by EventBoard.getInfoList().
     * @see EventBoard
     */
    public List<List<String>> getMyEventsInfoList(EventBoard eb, AccountManager acm) {
        List<List<String>> result = new ArrayList<>();
        List<Integer> myEventList = getMyEventList(eb);
        for (int event : myEventList) {
            result.add(eb.getInfoList(event, acm));
        }
        return result;
    }

}
