package event.gateway;

import event.useCases.ScheduleGenerator;

import java.io.*;
import java.util.List;

/**
 * Gateway for downloading and outputting schedule as html.
 */
public class ScheduleHTMLDownloader {
    /**
     * Downloads the table of schedule under the user's desktop and outputs it as html
     *
     * @param schedule a schedule generated by ScheduleGenerator.
     * @see ScheduleGenerator
     */
    public boolean write(List<List<String>> schedule){
        StringBuilder sb = new StringBuilder();
        sb.append("<html>");
        sb.append("<head>");
        sb.append("<title>Schedule</title>");
        sb.append("</head>");
        sb.append("<body>");
        sb.append("<style type = \"text/css\">");
        sb.append(".mytable{ margin:0 auto; }");
        sb.append("</style>");
        sb.append("<table class = \"mytable\" border = \"3\" cellspacing=\"0\">");
        sb.append("<caption><h2>Schedule</h2></caption>");
        for (List<String> row : schedule) {
            sb.append("<tr>");
            for (String s : row) {
                sb.append("<td align=\"center\"><h2>");
                sb.append(s);
                sb.append("</td></h2>");
            }
            sb.append("</tr>");
        }
        sb.append("</table>");
        sb.append("</body>");
        sb.append("</html>");

        try
        {
            FileWriter fw = new FileWriter("Schedule.html");
            BufferedWriter out = new BufferedWriter(fw);
            out.write(sb.toString());
            out.close();
            java.awt.Desktop.getDesktop().open(new File("Schedule.html"));
            return true;
        }
        catch (IOException ioe)
        {
            ioe.printStackTrace();
        }
        return false;
    }
}
